### ISSUE TITLE
Raindrop.create is not adding link to collection

### ISSUE THREAD

**Issue by tata-** [atsuoishimoto/python-raindropio#2]
I tried to run this and the bookmark created in the unsorted section and not in my collection

c = Collection.create(raindrop_api, title="Test collection")
Raindrop.create(raindrop_api, link="http://example.com", collection=c, tags=["test", "tag"])

Thanks,

ps:
Tried to check the code but I guess it is working fine

**Comment by atsuoishimoto** [comment]
Thank you for the issue!
I fixed the bug and made the new release(0.0.4).

Please update the python-raindropio and try again.
